from __future__ import annotations

import logging
import os
import pickle
from typing import Any

from app.core.rag.retriever import retrieve
from app.core.rag.generator import generate_answer
from app.core.intent.predictor import predict_intent
import app.services.embeddings.vector_store as _vs


logger = logging.getLogger(__name__)

# Retrieval parameter
_TOP_K = 3

# Tracks indexed source
_indexed_source: str | None = None

# 🔥 IMPORTANT: shared embeddings file path
EMBEDDINGS_PATH = "/data/embeddings.pkl"   # change if needed


# ---------------------------------------------------------------------------
# PUBLIC API
# ---------------------------------------------------------------------------

def run_rag_pipeline(
    query: str,
    source: str | None = None,
    intent: str = "factual",
    force_reindex: bool = False,
) -> dict[str, Any]:

    if not query or not query.strip():
        raise ValueError("Query must not be empty")

    if not source:
        return {
            "query": query,
            "intent": intent,
            "answer": "No document loaded yet. Please upload a document first.",
            "source_chunks": [],
            "num_chunks_retrieved": 0
        }

    # Intent detection (safe)
    try:
        predicted_intent = predict_intent(query)
        if predicted_intent:
            intent = predicted_intent
    except Exception:
        pass

    # Ensure FAISS index is ready
    _ensure_index_ready(source, force_reindex)

    # Retrieve relevant chunks
    context_chunks = retrieve(query, top_k=_TOP_K)

    # Generate answer
    answer = generate_answer(query, context_chunks, intent)

    return {
        "query": query,
        "intent": intent,
        "answer": answer,
        "source_chunks": context_chunks,
        "num_chunks_retrieved": len(context_chunks),
    }


def get_all_chunks(
    source: str | None = None,
    force_reindex: bool = False,
) -> list[str]:

    if not source:
        return []

    _ensure_index_ready(source, force_reindex)

    chunks = list(_vs.stored_chunks)

    return chunks if chunks else []


# ---------------------------------------------------------------------------
# INTERNAL
# ---------------------------------------------------------------------------

def _ensure_index_ready(source: str, force_reindex: bool = False) -> None:
    global _indexed_source

    # Avoid reloading same document
    if not force_reindex and _indexed_source == source:
        return

    try:
        # 🔥 Check embeddings file exists
        if not os.path.exists(EMBEDDINGS_PATH):
            logger.warning("Embeddings not ready yet (worker may still be processing)")
            return

        # 🔥 Load embeddings generated by worker
        with open(EMBEDDINGS_PATH, "rb") as f:
            chunks, embeddings = pickle.load(f)

        if not chunks or not embeddings:
            logger.warning("Empty embeddings file")
            return

        # 🔥 Store in FAISS
        from app.services.embeddings.vector_store import store_embeddings
        store_embeddings(chunks, embeddings)

        _indexed_source = source

        logger.info(f"Index ready with {len(chunks)} chunks")

    except Exception as e:
        logger.error(f"Failed to load embeddings: {e}")